services:
  app:
    image: app
    build:
      context: ./app
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8000:5000"
    volumes:
      - ./volume:/data
    depends_on:
      - service

  service:
    image: service
    build:
      context: ./service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./volume:/data

volumes:
  volume:
